### ISSUE TITLE
filename argument in export_data does not accept folder names.

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#801]
`filename` argument in `export_data` raises an error if the folder name is included. For instance, the following line won't run, whereas I think it makes sense for it should work.
```
OpenPNM.export_data(network=net, filename='./Networks/network')

**Comment by jgostick** [comment]
I think it would work if it were an absolute path.

**Comment by ma-sadeghi** [comment]
Yes, it works on absolute paths, breaks on relative paths though.

**Comment by jgostick** [comment]
hmmm...we'll have to dig into the file io parts on the GenericIO class and handle this properly.

**Comment by jgostick** [comment]
The following works, but then it become a question of knowing when the user has given a relative or absolute path:

```
import os
my_path = os.path.abspath('')
path = os.path.join(my_path, "../OpenPNM_V1/test/fixtures/test_load_vtk_no_phases.vtp")
```

Any path that starts with some dots would be a relative path, but only if the user wants to walk up the directory tree.  A relative path below the current directory just starts with a regular slash, but then it could be an absolute path on a *NIX system.  

Should we change the docstring to explicit say it should be an absolute path?  Should we rename the argument to 'abspath'?

**Comment by jgostick** [comment]
This is now fixed... @ma-sadeghi , can you confirm that it works the way you expect?  Remember that double dots mean up one level, so '../../file.vtp' will save two levels above the current working directory.

**Comment by ma-sadeghi** [comment]
@jgostick Apart from the fact that we don't have `export_data` on `openpnm` anymore, it works on `openpnm.io.VTK.save`.

**Comment by jgostick** [comment]
it's on the project object, so 

``` python
proj = pn.project
proj.export_data(network=pn)
```

**Comment by ma-sadeghi** [comment]
I pulled the latest commits but am still getting `'Project' object has no attribute 'export_data'`

**Comment by jgostick** [comment]
Hmmm...it's actually on workspace for some reason.  Is project a better place?

**Comment by ma-sadeghi** [comment]
Given that it accepts network as an argument, maybe it's for the best for it to be on workspace.
